---
## required meta-data -------------------------------------
output: example
title: 'markdown-memo example document'
titleshort: 'markdown-memo example document'
subtitle: 'make writing easier and more productive'
author:
    -   |
        [Ryan Reece](http://reece.scipp.ucsc.edu/)[^ReeceSCIPP]

        [^ReeceSCIPP]: University of California, Santa Cruz / <ryan.reece@cern.ch> / <http://reece.scipp.ucsc.edu>

    -   |
        Jane Coauthor[^JaneCoauthor]

        [^JaneCoauthor]: Joe University, Joeville
authorshort: 'R. Reece and J. Coauthor'
date: \today
#date: 'August 1, 2016'
draft: true
#license: ''
#license: '&copy; 2015-2016 Ryan Reece. All rights reserved.'
license: '<span class="copy-left">&copy;</span> 2015-2016 Ryan Reece. Licensed for sharing under [CC-BY-4.0](http://creativecommons.org/licenses/by/4.0/).'
dorefs: true
submitted: ''
#submitted: 'Submitted to My Favorite Journal'
#submitted: 'Journal reference: *Phys. Rev. D 92*, 072001 (2015)'
## optional -----------------------------------------------
abstract: |
    This is an example document discussing and demonstrating
    how to use the markdown-memo package,
    meant to aid quick development of quality html and pdf
    documents from simple Markdown markup.
    Markdown-memo is developed by Ryan Reece at
    [https://github.com/rreece/markdown-memo](https://github.com/rreece/markdown-memo).

    *Keywords:* academic writing, blogging, digital humanities, LaTeX, Markdown,
    open publishing, open science, productivity, technical writing, typesetting, writing
figureTitle: "Figure"
tableTitle: "Table"
figPrefix: "Figure"
eqnPrefix: "eq."
secPrefix: "Section"
tblPrefix: "Table"
## html options -------------------------------------------
css: 'templates/markdown-memo.css'
#css: 'templates/markdown-memo-alt.css'
email: '<img class="email" src="img/my_email.png" alt="my email address"/>'
#email: '<img class="email" src="img/my-email-alt.png" alt="my email address"/>'
#disqus: true
#disqus_shortname: 'my-sites-disqus-name'
#description: 'Write a description of this page.'
favicon: '/img/markdown-favicon-196x196.png'
#google_analytics_tracking_id: 'UA-XXXXXXXX-X'
#keywords: 'List, some, keywords, for, this, webpage'
mathjax: true
navigation: true
thumbnail: 'http://rreece.github.io/sw/markdown-memo/img/ATLAS-local-p0-vs-mH.png'
## pdflatex options ---------------------------------------
classoption:
    -   'openany'
    -   'twoside'
citation-style: 'templates/apa-no-doi-no-issue-with-notes.csl'
fancyhdr: true
fontfamily: 'mathpazo'
fontsize: '11pt'
geometry: 
    -   'paperwidth=8.5in'
    -   'paperheight=11in'
    -   'top=1in'
    -   'bottom=1in'
    -   'left=1.25in'
    -   'right=1.25in'
    -   'headheight=14pt'
    -   'headsep=14pt'
#linestretch: '0.9'
lof: false
lot: false
maketitle: true
numbersections: true
parskip: '11pt'
spacing: '1.2'
toc: true
toc-depth: 3
...

