---
title: 'This is the title: it contains a colon'
titleshort: 'This is the title'
author:
    -   |
        Ryan Reece[^ReeceSCIPP]

        [^ReeceSCIPP]: University of California, Santa Cruz

    -   |
        Coauthor Joe[^CoauthorJoe]

        [^CoauthorJoe]: Joe University, Joeville
authorshort: 'R. Reece and C. Joe'
date: 'August 1, 2015'
license: 'Licensed for sharing under [CC-BY-4.0](http://creativecommons.org/licenses/by/4.0/)'
## ^ required meta-data ^ ---------------------------------
abstract: |
    \noindent This is the abstract. This is the abstract. This is the abstract.
    This is the abstract. This is the abstract. This is the abstract.
    This is the abstract. This is the abstract. This is the abstract.

    This is the second paragraph in the abstract.
    This is the second paragraph in the abstract.
    This is the second paragraph in the abstract.
## html options -------------------------------------------
#disqus: true
#disqus_shortname: 'my-sites-disqus-name'
## pdflatex options ---------------------------------------
fontsize: '11pt'
fontfamily: 'mathpazo'
#linestretch: '1.1'
numbersections: true
spacing: '1.2'
geometry: 
    -   'paperwidth=8.5in'
    -   'paperheight=11in'
    -   'top=1in'
    -   'bottom=1in'
    -   'left=1.5in'
    -   'right=1.5in'
    -   'headheight=14pt'
    -   'headsep=\baselineskip'
fancyhdr: true
classoption:
    -   'openany'
    -   'twoside'
natbib: true
biblio-style: 'chicago'
...

