---
## required meta-data -------------------------------------
title: 'This is the title: it contains a colon'
titleshort: 'This is the title'
subtitle: 'This is the subtitle'
author:
    -   |
        Ryan Reece[^ReeceSCIPP]

        [^ReeceSCIPP]: University of California, Santa Cruz

    -   |
        Joe Coauthor[^JoeCoauthor]

        [^JoeCoauthor]: Joe University, Joeville
authorshort: 'R. Reece and J. Coauthor'
date: 'August 1, 2016'
#license: ''
#license: '&copy; 2015-2016 Ryan Reece. All rights reserved'
license: 'Licensed for sharing under [CC-BY-4.0](http://creativecommons.org/licenses/by/4.0/)'
## optional -----------------------------------------------
abstract: |
    This is the abstract. This is the abstract. This is the abstract.
    This is the abstract. This is the abstract. This is the abstract.
    This is the abstract. This is the abstract. This is the abstract.
    This is the abstract. This is the abstract. This is the abstract.

    This is the second paragraph in the abstract.
    This is the second paragraph in the abstract.
    This is the second paragraph in the abstract.
figureTitle: "Figure"
tableTitle: "Table"
figPrefix: "Figure"
eqnPrefix: "eq."
tblPrefix: "Table"
## html options -------------------------------------------
email: '<img class="email" src="img/my_email.png" alt="my email address"/>'
#disqus: true
#disqus_shortname: 'my-sites-disqus-name'
#description: 'Write a description of this webpage.'
#keywords: 'List, some, keywords, for, this, webpage'
#google_analytics_tracking_id: 'UA-XXXXXXXX-X'
mathjax: true
## pdflatex options ---------------------------------------
fontsize: '11pt'
fontfamily: 'mathpazo'
#linestretch: '0.9'
numbersections: true
spacing: '1.2'
geometry: 
    -   'paperwidth=8.5in'
    -   'paperheight=11in'
    -   'top=1in'
    -   'bottom=1in'
    -   'left=1.5in'
    -   'right=1.5in'
    -   'headheight=14pt'
    -   'headsep=\baselineskip'
fancyhdr: true
classoption:
    -   'openany'
    -   'twoside'
natbib: true
biblio-style: 'chicago'
...

