---
## required meta-data -------------------------------------
title: 'This is the title: it contains a colon'
titleshort: 'This is the title'
subtitle: 'This is the subtitle'
author:
    -   |
        [Ryan Reece](http://reece.scipp.ucsc.edu/)[^ReeceSCIPP]

        [^ReeceSCIPP]: University of California, Santa Cruz / <ryan.reece@cern.ch> / <http://reece.scipp.ucsc.edu>

    -   |
        Joe Coauthor[^JoeCoauthor]

        [^JoeCoauthor]: Joe University, Joeville
authorshort: 'R. Reece and J. Coauthor'
date: 'August 1, 2016'
#license: ''
#license: '&copy; 2015-2016 Ryan Reece. All rights reserved'
license: '<span class="copy-left">&copy;</span> 2015-2016 Ryan Reece. Licensed for sharing under [CC-BY-4.0](http://creativecommons.org/licenses/by/4.0/)'
## optional -----------------------------------------------
abstract: |
    This is the abstract. This is the abstract. This is the abstract.
    This is the abstract. This is the abstract. This is the abstract.
    This is the abstract. This is the abstract. This is the abstract.
    This is the abstract. This is the abstract. This is the abstract.

    This is the second paragraph in the abstract.
    This is the second paragraph in the abstract.
    This is the second paragraph in the abstract.

    \textsc{keywords}: Quantum field theory, QFT, quantization, second quantization, wave-particle duality
figureTitle: "Figure"
tableTitle: "Table"
figPrefix: "Figure"
eqnPrefix: "eq."
tblPrefix: "Table"
## html options -------------------------------------------
email: '<img class="email" src="img/my_email.png" alt="my email address"/>'
#disqus: true
#disqus_shortname: 'my-sites-disqus-name'
#description: 'Write a description of this webpage.'
#keywords: 'List, some, keywords, for, this, webpage'
#google_analytics_tracking_id: 'UA-XXXXXXXX-X'
mathjax: true
## pdflatex options ---------------------------------------
fontsize: '11pt'
fontfamily: 'mathpazo'
#linestretch: '0.9'
numbersections: true
spacing: '1.2'
geometry: 
    -   'paperwidth=8.5in'
    -   'paperheight=11in'
    -   'top=1in'
    -   'bottom=1in'
    -   'left=1.25in'
    -   'right=1.25in'
    -   'headheight=14pt'
    -   'headsep=14pt'
fancyhdr: true
classoption:
    -   'openany'
    -   'twoside'
citation-style: 'templates/apa-no-doi-no-issue.csl'
...

